spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voting_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
      initialization-fail-timeout: 30000
  docker:
    compose:
      lifecycle-management: start_only
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          provider_disables_autocommit: true
        # Hibernate Envers properties
        envers:
          audit_table_suffix: _audit
          revision_field_name: rev
          revision_type_field_name: revtype
          store_data_at_delete: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      connect-timeout: 2000
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes
      cache-null-values: false
      use-key-prefix: true

server:
  port: 8090
